from django.urls import path, include
from . import views
# app_name = 'lessons'
urlpatterns = [
    path('', views.lessons, name='lessons'),
    path('HTML/', views.htmlOb, name='html'),
    path('CSS-1/', views.cssOb1, name='css1'),
    path('CSS-2/', views.cssOb2, name='css2'),
    path('JavaScript/', views.bootstrapOb, name='bootstrap'),
    path('HTML/№1/', views.les1, name='html-1'),
    path('HTML/№2/', views.les2, name='html-2'),
    path('HTML/№3/', views.les3, name='html-3'),
    path('HTML/№4/', views.les4, name='html-4'),
    path('HTML/№5/', views.les5, name='html-5'),
    path('HTML/№6/', views.les6, name='html-6'),
    path('HTML/№7/', views.les7, name='html-7'),
    path('HTML/№8/', views.les8, name='html-8'),
    path('HTML/№9/', views.les9, name='html-9'),
    path('HTML/№10/', views.les10, name='html-10'),
    path('HTML/№11/', views.les11, name='html-11'),
    path('HTML/test1/', views.test1, name='test1'),
    path('HTML/test2/', views.test2, name='test2'),
    path('HTML/test3/', views.test3, name='test3'),
    path('HTML/practice/', views.pra, name='pra'),
    path('HTML/practice/example/', views.ex, name='ex'),
    path('CSS-1/№1/', views.less1),
    path('CSS-1/№2/', views.less2),
    path('CSS-1/№3/', views.less3),
    path('CSS-1/№4/', views.less4),
    path('CSS-1/№5/', views.less5),
    path('CSS-1/№6/', views.less6),
    path('CSS-1/№7/', views.less7),
    path('CSS-1/test1/', views.test11),
    path('CSS-1/test2/', views.test22),
    path('CSS-1/test3/', views.test33),
    path('CSS-1/practice/', views.praCS),
    path('CSS-1/practice/example/', views.exs),
]